### ISSUE TITLE
Fails at "make menuconfig"

### ISSUE THREAD

**Issue by HeinzAlberto** [d3v1c3nv11/sip_phone_example#1]
Hi there!

I can not bring the project to work...
When I run "make menuconfig", it just fails (see Screenshot)

It seems like it is missing the file curses.h - where should that file be and from where do I get it? Or am I just doing the setup wrong?

![grafik](https://user-images.githubusercontent.com/18151901/90534527-20286780-e17a-11ea-872b-bd439ae9c672.png)

I would be very happy if you help me with that!

Thank you a Lot!
~ Heinz

**Comment by HeinzAlberto** [comment]
Found the error!
Run:

pip install ncurses

**Comment by can-caglar** [comment]
Above didn't work for me but this did:

sudo apt-get install libncurses5-dev libncursesw5-dev
