### ISSUE TITLE
AUDIO_THREAD: Error creating task input_key_service

### ISSUE THREAD

**Issue by HeinzAlberto** [d3v1c3nv11/sip_phone_example#4]
To say it short: There seems to be a NULL POINTER EXCEPTION in the code...
See the last serial prints he did before crashing and rebooting to crash again:
![grafik](https://user-images.githubusercontent.com/18151901/90548451-3e4b9300-e18d-11ea-9989-8d1c273e6f75.png)

So, what should I do? Is it a configuration problem or is it a problem in the code?

**Comment by HeinzAlberto** [comment]
I replayed the g711.h from issue #2 with the esp_g711.h in voip_app.c, which is already there.

The error is there anyway...

**Comment by HeinzAlberto** [comment]
I noticed, that I get an error while "make" is running:
![grafik](https://user-images.githubusercontent.com/18151901/90556080-96d45d80-e198-11ea-954c-cb63b5f3bd9b.png)

It is about input_key_service, just like the error itself. Pretty sure it has to do something with it...

**Comment by HeinzAlberto** [comment]
Hi there, 
the error also exists with the update from October 2020.

It appears right after connecting to WiFi. 
So it still has the same problem with starting the input key service.

Anyone have an idea how to fix it?
(See screenshot)
![grafik](https://user-images.githubusercontent.com/18151901/111889960-68945600-89e5-11eb-90ab-bae0ad14e004.png)

**Comment by can-caglar** [comment]
I managed to find a way around the issue. 

It looks like Olimex is using calls from a different (older?) esp library, so the program doesn't work correctly.

Here is the fix that works for me:

In `voip_app.c` comment out `lines 485 to 489` and replace with the following. Recompile, flash and should work :):

```
ESP_LOGI(TAG, "[ 3 ] Create and start input key service V2");
input_key_service_info_t input_key_info[] = INPUT_KEY_DEFAULT_INFO();
input_key_service_cfg_t input_cfg = INPUT_KEY_SERVICE_DEFAULT_CONFIG();
input_cfg.handle = set;
periph_service_handle_t input_ser = input_key_service_create(&input_cfg);
input_key_service_add_key(input_ser, input_key_info, INPUT_KEY_NUM);
periph_service_set_callback(input_ser, input_key_service_cb, (void *)board_handle);
```

**Comment by HeinzAlberto** [comment]
Funny, I wanted to write the same thing just now :-D

**Comment by d3v1c3nv11** [comment]
> I managed to find a way around the issue.
> 
> It looks like Olimex is using calls from a different (older?) esp library, so the program doesn't work correctly.
> 
> Here is the fix that works for me:
> 
> In `voip_app.c` comment out `lines 485 to 489` and replace with the following. Recompile, flash and should work :):
> 
> ```
> ESP_LOGI(TAG, "[ 3 ] Create and start input key service V2");
> input_key_service_info_t input_key_info[] = INPUT_KEY_DEFAULT_INFO();
> input_key_service_cfg_t input_cfg = INPUT_KEY_SERVICE_DEFAULT_CONFIG();
> input_cfg.handle = set;
> periph_service_handle_t input_ser = input_key_service_create(&input_cfg);
> input_key_service_add_key(input_ser, input_key_info, INPUT_KEY_NUM);
> periph_service_set_callback(input_ser, input_key_service_cb, (void *)board_handle);
> ```

Patch merged. Thanks!
