### ISSUE TITLE
Can't "make" after reboot

### ISSUE THREAD

**Issue by HeinzAlberto** [d3v1c3nv11/sip_phone_example#5]
After rebooting the computer, running "make menuconfig" I get an error. Have this problem every time I reboot my computer - so I have to rebuild the whole project every time (which is a bit of annoying ^_^'').
Am I just doing something wring or is there a error in the project?

![grafik](https://user-images.githubusercontent.com/18151901/90572722-0b1cfa00-e1b5-11ea-9286-9702f2d005c1.png)
(English:
Makefile:8: /project.mk: File or Directory not found.
make: ** No rule for creating "/project.mk". End.)

Thank you for any help!

**Comment by d3v1c3nv11** [comment]
Set the path to esp-adf sdk first:
`export ADF_PATH={full path where esp-adf is installed}`

**Comment by HeinzAlberto** [comment]
Thank you, it works now!
In my case:

export ADF_PATH=/home/felix/esp-adf
(Where "felix" is the username)

**Comment by HeinzAlberto** [comment]
Just found out - if you want to have ADF_PATH automatically set in your terminal, you can just add the export command to your local .bashrc file.
On Debian based systems run:

cd ~
sudo nano .bashrc        _(if you are root, leaf the "sudo" out)_
_(got to the end of the file and write into a new line)_        export ADF_PATH=/home/**YOUR_USERNAME**/esp-adf
_(save and close the file)_
source .bashrc        _(loads the chanced file)_
